apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 5
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      trafficRouting:
        istio:
          virtualService:
            name: rollout-vsvc
            routes:
            - primary
          destinationRule:
            name: rollout-destrule
            canarySubsetName: canary
            stableSubsetName: stable  
      steps:
      - setWeight: 5
      - pause:
          duration: 10s # 10 sec
      - setWeight: 20
      - pause:
          duration: 10s # 10 sec
      - setWeight: 40
      - pause:
          duration: 10s # 10 sec
      - setWeight: 60
      - pause:
          duration: 10s # 10 sec
      - setWeight: 80
      - pause:
          duration: 10s # 10 sec

  revisionHistoryLimit:2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - name: http
        - containerPort: 80
          protocal: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m

